version: '3'

networks:
  rabbitnet:
    name: rabbitnet
    driver: bridge

services:
  producer:
    build: producer
    networks:
      - rabbitnet
    depends_on:
      - rmq
  consumer:
    build: consumer
    networks:
      - rabbitnet
    depends_on:
      - rmq
  rmq:
    build: rmq
    hostname: rabbitmq
    networks:
      - rabbitnet
    ports:
      # HOST:CONTAINER
      - 15672:15672
